python finetune_main.py \
    --downstream_dataset 'SEED-V' \
    --num_of_classes 5 \
    --model_dir './models_my' \
    --num_workers 4 \
    --datasets_dir "../BigDownstream/SEED-V/processed" \
    --cuda 0 \
    --lr 0.002 \
    --batch_size 32 \
    --multi_lr False \
    --epochs 50 \
    --weight_decay 5e-2 \
    --clip_value -1