python finetune_main.py \
    --downstream_dataset 'SHU-MI' \
    --num_of_classes 1 \
    --model_dir './models_my' \
    --num_workers 4 \
    --datasets_dir "../BigDownstream/shu_datasets" \
    --cuda 0 \
    --batch_size 16 \
    --lr 0.001 \
    --multi_lr False \
    --epochs 20 \
    --weight_decay 1e-4 \
    --clip_value -1
